-- ============================================================================
--  0027: personal workspaces, self-registration, a credential vault, tables
--        modelled into the ontology, and proposals that wait for approval.
--
--  The platform was built for one team reading one TMS snapshot: every user
--  saw the same four environment spaces, a connection's password was the NAME
--  of a server-side secret, and the ontology only ever came from the pipeline.
--  This migration is the schema half of turning that into something a person
--  can sign up to, connect their own PostgreSQL tables to, and build on:
--
--    * a personal space per user, which only its owner (and admins) can
--      open - their connections, datasets, ontology, metrics, dashboards and
--      conversations live there and nowhere else;
--    * membership for the shared environment spaces, so a self-registered
--      user does not see the team's sandbox by default;
--    * an encrypted credential vault, because a personal workspace cannot be
--      allowed to name a server-side secret (that would let anyone who can
--      register point a connection at their own host and receive the
--      platform's database password);
--    * provenance on object types, links and metrics that are modelled from
--      connected tables rather than generated by the pipeline;
--    * proposals: links, metrics, combined datasets and action types the
--      assistant (or a person) asks for, held until someone approves them.
--
--  Nothing here generates data. Every new table describes structure, access
--  or intent.
-- ============================================================================

-- ── users ───────────────────────────────────────────────────────────────────

ALTER TABLE platform.app_user ADD COLUMN IF NOT EXISTS email TEXT;
-- How the account came to exist. 'self' accounts are the ones that must not
-- see the shared environment spaces until someone adds them.
ALTER TABLE platform.app_user ADD COLUMN IF NOT EXISTS signup_source TEXT NOT NULL DEFAULT 'admin';
ALTER TABLE platform.app_user DROP CONSTRAINT IF EXISTS app_user_signup_source_check;
ALTER TABLE platform.app_user
    ADD CONSTRAINT app_user_signup_source_check CHECK (signup_source IN ('admin','bootstrap','self'));
CREATE UNIQUE INDEX IF NOT EXISTS ux_app_user_email
    ON platform.app_user (lower(email)) WHERE email IS NOT NULL;

-- ── spaces: shared environments and personal workspaces ─────────────────────

ALTER TABLE platform.space ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'environment';
ALTER TABLE platform.space DROP CONSTRAINT IF EXISTS space_kind_check;
ALTER TABLE platform.space ADD CONSTRAINT space_kind_check CHECK (kind IN ('environment','personal'));
ALTER TABLE platform.space ADD COLUMN IF NOT EXISTS owner_username TEXT;
ALTER TABLE platform.space DROP CONSTRAINT IF EXISTS space_owner_check;
ALTER TABLE platform.space
    ADD CONSTRAINT space_owner_check CHECK ((kind = 'personal') = (owner_username IS NOT NULL));
CREATE UNIQUE INDEX IF NOT EXISTS ux_space_personal_owner
    ON platform.space (owner_username) WHERE kind = 'personal';

-- Who may open a shared environment space. Accounts an administrator created
-- keep seeing every environment space without a row here, which is how the
-- platform behaved before this migration; a self-registered account needs
-- one. Personal spaces are never shared through this table.
CREATE TABLE IF NOT EXISTS platform.space_member (
    space_id   BIGINT NOT NULL REFERENCES platform.space(space_id) ON DELETE CASCADE,
    username   TEXT NOT NULL,
    role       TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer','editor')),
    added_by   TEXT NOT NULL,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (space_id, username)
);

-- ── the credential vault ────────────────────────────────────────────────────
--  A password typed into the connection form, encrypted with AES-256-GCM. The
--  key is not in the database (CREDENTIAL_KEY_FILE, or derived from the JWT
--  secret), so a backup of this table is not a list of passwords. A credential
--  belongs to one space and can only be used by a connection in that space.
CREATE TABLE IF NOT EXISTS platform.credential (
    credential_id BIGSERIAL PRIMARY KEY,
    space_id      BIGINT NOT NULL REFERENCES platform.space(space_id) ON DELETE CASCADE,
    label         TEXT NOT NULL,
    ciphertext    TEXT NOT NULL,
    iv            TEXT NOT NULL,
    auth_tag      TEXT NOT NULL,
    -- A fingerprint of the key that encrypted it, so a rotated key is reported
    -- as such rather than producing a failed decryption that reads as a bad
    -- password on the remote host.
    key_id        TEXT NOT NULL,
    created_by    TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_credential_space ON platform.credential (space_id);

-- ── provenance of ontology objects ──────────────────────────────────────────

-- Rows already there came from the retired generator; from here on a type is
-- authored by hand or by the assistant (the default), modelled automatically
-- when a table is imported, or a combination of linked types.
ALTER TABLE platform.object_type ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'pipeline';
ALTER TABLE platform.object_type ALTER COLUMN origin SET DEFAULT 'authored';
ALTER TABLE platform.object_type DROP CONSTRAINT IF EXISTS object_type_origin_check;
ALTER TABLE platform.object_type
    ADD CONSTRAINT object_type_origin_check CHECK (origin IN ('pipeline','authored','modelled','combination'));
-- The dataset resource a modelled type was built from, so the two can be
-- shown together and the type rebuilt when the dataset is re-synced.
ALTER TABLE platform.object_type ADD COLUMN IF NOT EXISTS dataset_resource_id BIGINT;
-- False when no column of the source was unique, so opening one object by
-- its key may match several rows. Said rather than hidden.
ALTER TABLE platform.object_type ADD COLUMN IF NOT EXISTS key_is_unique BOOLEAN NOT NULL DEFAULT true;

-- A foreign key read from the source database's own catalogue is the
-- strongest evidence a link can have, and is recorded as such.
ALTER TABLE platform.link_type DROP CONSTRAINT IF EXISTS link_type_discovery_method_check;
ALTER TABLE platform.link_type
    ADD CONSTRAINT link_type_discovery_method_check CHECK (discovery_method IN (
        'naming_convention','declared_hierarchy','value_overlap','manual','foreign_key'));

-- ── metrics ─────────────────────────────────────────────────────────────────

-- A metric's own filters ("revenue from completed orders") are the
-- conditions column of 0031. Where it came from: the retired catalogue,
-- authored on an object type, modelled with an imported table, or approved
-- from a proposal.
ALTER TABLE platform.kpi_definition ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'catalogue';
ALTER TABLE platform.kpi_definition ALTER COLUMN origin SET DEFAULT 'authored';
ALTER TABLE platform.kpi_definition DROP CONSTRAINT IF EXISTS kpi_definition_origin_check;
ALTER TABLE platform.kpi_definition
    ADD CONSTRAINT kpi_definition_origin_check CHECK (origin IN ('catalogue','authored','modelled','proposal'));
ALTER TABLE platform.kpi_definition ADD COLUMN IF NOT EXISTS object_type_rid TEXT;
ALTER TABLE platform.kpi_definition ADD COLUMN IF NOT EXISTS created_by TEXT;

-- ── dashboards and reports ──────────────────────────────────────────────────

-- A report is a dashboard read top to bottom and printed: the same widgets,
-- laid out as a document with its narrative between them.
ALTER TABLE platform.dashboard ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'dashboard';
ALTER TABLE platform.dashboard DROP CONSTRAINT IF EXISTS dashboard_kind_check;
ALTER TABLE platform.dashboard ADD CONSTRAINT dashboard_kind_check CHECK (kind IN ('dashboard','report'));

-- ── where a synced table came from ──────────────────────────────────────────

-- The source table's primary key and foreign keys, read from the remote
-- catalogue when the table is imported. They are what turns a pile of synced
-- tables into object types with real keys and real links.
ALTER TABLE platform.connection_sync ADD COLUMN IF NOT EXISTS source_primary_key TEXT[];
ALTER TABLE platform.connection_sync
    ADD COLUMN IF NOT EXISTS source_foreign_keys JSONB NOT NULL DEFAULT '[]'::jsonb;

-- ── combinations: object types joined along their links ─────────────────────
--  "Orders with their customer's segment" is a view over two synced tables,
--  joined on a link that already exists. The SQL is generated from the link
--  and the chosen properties - never written by the caller - and kept here so
--  the view can be rebuilt when one of its tables is re-synced.
CREATE SCHEMA IF NOT EXISTS ontology_views;

CREATE TABLE IF NOT EXISTS platform.combination (
    combination_id BIGSERIAL PRIMARY KEY,
    space_id       BIGINT NOT NULL REFERENCES platform.space(space_id) ON DELETE CASCADE,
    api_name       TEXT NOT NULL,
    view_name      TEXT NOT NULL UNIQUE,
    definition     JSONB NOT NULL,
    sql            TEXT NOT NULL,
    created_by     TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (space_id, api_name)
);

-- ── proposals ───────────────────────────────────────────────────────────────
--  Something the ontology does not have yet - a link, a metric, a combined
--  dataset, an action type - drafted by the assistant or a person and applied
--  only when someone approves it. The payload is validated when the proposal
--  is made and again when it is applied, because the ontology can change in
--  between.
CREATE TABLE IF NOT EXISTS platform.proposal (
    proposal_id     BIGSERIAL PRIMARY KEY,
    space_id        BIGINT NOT NULL REFERENCES platform.space(space_id) ON DELETE CASCADE,
    kind            TEXT NOT NULL
                    CHECK (kind IN ('link_type','metric','combination','action_type')),
    title           TEXT NOT NULL,
    summary         TEXT,
    payload         JSONB NOT NULL,
    -- What approving it would do, measured when it was proposed: the match
    -- ratio of a link, the headline value of a metric, sample rows of a join.
    preview         JSONB NOT NULL DEFAULT '{}'::jsonb,
    status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','applied','rejected','failed')),
    -- Proposals that must be applied first, e.g. the link a combination joins on.
    depends_on      BIGINT[] NOT NULL DEFAULT '{}',
    result          JSONB,
    error           TEXT,
    created_by      TEXT NOT NULL,
    created_via     TEXT NOT NULL DEFAULT 'user'
                    CHECK (created_via IN ('user','assistant','planner')),
    chat_session_id BIGINT REFERENCES platform.chat_session(chat_session_id) ON DELETE SET NULL,
    decided_by      TEXT,
    decided_at      TIMESTAMPTZ,
    decision_note   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_proposal_space_status
    ON platform.proposal (space_id, status, created_at DESC);
