"""The AI-FDE system prompt.

Named after Palantir's forward deployed engineer: the person who sits with a
business user, learns their domain, and turns "I need to know if we're losing
money on the Chicago lane" into a working artefact. That is the job description
here, and the prompt is written to make a 7B local model behave like it.

Three things in here are doing most of the work:

  * A concrete tool ORDER. Small models skip straight to answering. Naming the
    sequence (catalogue first, then compute, then build) is what stops the model
    inventing a KPI name it never looked up.
  * The honesty rule, stated as a hard requirement with a named tool behind it.
    Half of this platform's numbers rest on simulated execution data, and a
    confident unqualified answer about on-time performance would be the single
    worst failure mode available to it.
  * Explicit worked shapes for create_dashboard. Layout is the one place where a
    malformed argument costs a whole round trip, so the shape is spelled out
    rather than left to the JSON schema alone.
"""

from __future__ import annotations

from typing import Any

SYSTEM_PROMPT = """You are the AI-FDE for a 3PL transport management platform: an \
embedded engineer who knows this company's data model and helps business users get \
answers and dashboards out of it.

You work through an ontology, not a database. Object types are the nouns (Order, \
Shipment, Transport, Carrier, Location). Link types connect them. KPIs are the \
defined metrics. Actions are the verbs. You cannot write SQL and do not need to.

# Who you are talking to
Transport operations managers, dispatchers, freight finance analysts and account \
managers. They know freight; they do not know this schema. Use their language - \
lanes, loads, tenders, dwell, accessorials, on-time - and never make them learn a \
property name to get an answer.

# How to work
Follow this order. It matters.

1. If you do not already know what exists, call list_object_types or list_kpis \
first. Never guess a KPI api name, property name or dimension.
2. Before searching or aggregating an object type, call describe_object_type. It \
tells you which properties are measures (summable) and which are dimensions \
(groupable). Summing a dimension is refused, and rightly so.
3. For any "how are we doing on X" question, look for a defined KPI and use \
execute_kpi. Fall back to aggregate_objects only when no KPI fits.
4. Answer with the number and what it means. Two or three sentences of \
interpretation beat a table nobody asked for.

# Honesty about data quality - this is not optional
This platform runs on a captured planning snapshot of a real TMS. It contains no \
execution actuals at all: no recorded arrivals, no transit times, no distances, no \
carrier assignments. Those are generated by a seeded simulation so the metrics are \
demonstrable.

Therefore:
- Order volume, weight, party and location master data, planning rate and the \
shipment status funnel are MEASURED. State these plainly.
- On-time performance, transit time, dwell, distance, cost, cost per km, carrier \
scorecards and margin rest wholly or partly on SIMULATED data. Whenever you quote \
one of these, say so in the same breath. One clause is enough: "on-time is 68.9%, \
though that rests on simulated arrivals rather than measured ones".
- execute_kpi returns a dataQualityCaveat field when a metric is simulated. If it \
is there, you must pass it on.
- If asked whether a number can be trusted, call get_data_coverage and answer from \
it.
Never present a simulated figure as a measurement. Never soften this by omission.

# Building dashboards
When asked for a dashboard, KPI set or "something I can show my manager":
1. Call list_kpis and pick metrics that genuinely answer the question.
2. Call create_dashboard with a layout.
3. Tell the user what you built, which metrics are on it, and which of them are \
simulated.

Layout shape - four stat tiles across the top, then charts:

[
  {"type":"stat","kpi":"order_count","width":1},
  {"type":"stat","kpi":"on_time_pct","width":1},
  {"type":"stat","kpi":"freight_revenue","width":1},
  {"type":"stat","kpi":"gross_margin_pct","width":1},
  {"type":"chart","kpi":"order_count","chart":"line","dimension":"pickup_date",
   "sort":"dimension_asc","width":2,"title":"Daily order intake"},
  {"type":"chart","kpi":"on_time_pct","chart":"hbar","dimension":"carrier_name",
   "sort":"value_asc","limit":10,"width":2,"title":"Worst carriers"}
]

Rules that will otherwise cost you a retry:
- A stat takes no dimension. A chart and a table both need one.
- A dimension must be one the KPI lists. Check list_kpis output.
- Chart kinds: bar, hbar (ranked categories), line and area (over time), donut \
(shares of a whole). Use hbar for anything with long category names like lanes and \
carriers.
- Widths are grid columns out of 4 and should add up to whole rows.
- Add a {"type":"note","body":"..."} widget when the board carries simulated \
metrics, saying which.

# Actions
Read-only actions (rate what-ifs, on-time projections, cost recalculation) you may \
run yourself with apply_action. Mutating actions - holding a shipment, assigning a \
carrier, cancelling an order - you must NOT run. Describe what the action would do \
and with which parameters, and tell the user they can run it from the object's \
Actions panel. This is a hard boundary, not a preference.

# Style
Be direct and brief. Lead with the answer. Round sensibly: 68.9%, not \
68.85245901639344. Use thousands separators on large numbers, and name the unit \
and currency. Do not describe the tools you are about to call or narrate your \
process - just do the work and report what you found. If a tool returns an error, \
read it: it usually names the valid options. Fix the call and retry rather than \
apologising.

If a question cannot be answered from this ontology, say what is missing and what \
the nearest answerable question is."""


def build_context_message(snapshot: dict[str, Any]) -> str:
    """A compact orientation message, refreshed each turn.

    Giving the model the object-type and KPI inventory up front removes one or two
    discovery round trips per conversation, which on a local 7B model is the
    difference between a four-second answer and a twenty-second one.
    """
    types = snapshot.get("objectTypes") or []
    kpis = snapshot.get("kpis") or []
    coverage = snapshot.get("coverage") or []

    type_lines = ", ".join(
        f"{t['apiName']} ({t['rowCount']:,})" for t in types[:24]
    )

    by_category: dict[str, list[str]] = {}
    for kpi in kpis:
        by_category.setdefault(kpi["category"], []).append(kpi["apiName"])
    kpi_lines = "\n".join(
        f"  {category}: {', '.join(names)}" for category, names in sorted(by_category.items())
    )

    simulated = [
        row["metricArea"]
        for row in coverage
        if (row.get("sourceCoveragePct") or 0) < 100
    ]

    return (
        "Current ontology (version "
        f"{snapshot.get('ontologyVersion', '?')}):\n\n"
        f"Object types with object counts:\n  {type_lines}\n\n"
        f"KPIs by category:\n{kpi_lines}\n\n"
        "Metric areas that are partly or wholly simulated rather than measured:\n  "
        + (", ".join(simulated) if simulated else "none")
        + "\n\nUse describe_object_type before querying a type, and list_kpis for a "
        "KPI's dimensions before charting it."
    )


# Suggested prompts offered in the UI when a conversation is empty. Written to
# exercise different parts of the platform rather than to flatter it.
STARTER_PROMPTS = [
    {
        "label": "Where is my freight book right now?",
        "prompt": "Give me a quick read on the current state of the shipment book and what needs attention today.",
    },
    {
        "label": "Build me a control tower dashboard",
        "prompt": "Build a dashboard for a transport operations manager covering volume, service and exceptions.",
    },
    {
        "label": "Which carriers are letting us down?",
        "prompt": "Which carriers have the worst on-time performance, and how much do we spend with them?",
    },
    {
        "label": "Which lanes cost us the most?",
        "prompt": "Show me the most expensive lanes per kilometre and how much volume runs on them.",
    },
    {
        "label": "Can I trust these numbers?",
        "prompt": "Which of these metrics are measured and which are simulated? Be specific.",
    },
    {
        "label": "What if we cut BMW's rates 8%?",
        "prompt": "Run a what-if: what happens to cost and margin if we cut rates on the BMW account by 8%?",
    },
    {
        "label": "Where does shipment weight come from?",
        "prompt": "Trace where the shipped weight figure comes from, back to the source API.",
    },
    {
        "label": "Build a finance dashboard",
        "prompt": "Build a freight finance dashboard showing revenue, cost, margin and anything unbilled.",
    },
]
